### ISSUE TITLE
Attribute Error

### ISSUE THREAD

**Issue by dontellpapa** [npmccallum/python-rubenesque#11]
Hello:

For testing purpose of ECC, I tried to install this package in my PC (Windows 10) and tried to follow certain steps shown in the README.MD. However, when I ran the the 3rd line code, I got an error as following:

>>> secp256r1 = rubenesque.curves.by_name('secp256r1')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'by_name'

I also tried this line of code in Linux environment and got the same error.
Can someone please try this and see if it gets to work?
Did I do something wrong?

Thank you.
![Rubenesque-AttributError](https://user-images.githubusercontent.com/64164716/139503230-06a7c8ab-b683-4be1-b00f-aee622255a54.jpg)

Bobby

**Comment by npmccallum** [comment]
@dontellpapa The documentation was incorrect. See the pull request I just merged. #6
