### ISSUE TITLE
setup.py references README, while README has been renamed to README.md

### ISSUE THREAD

**Issue by sundarnagarajan** [npmccallum/python-rubenesque#4]
Because of this 'python setup.py install'  fails with following error:

```
Traceback (most recent call last):
  File "setup.py", line 47, in <module>
    long_description=read('README'),
  File "setup.py", line 28, in read
    with open(fname) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'README'

```

**Comment by npmccallum** [comment]
Fixed in 8d04823e270b55633dd064e8e038cd8dd72cfc69. Thanks for the contribution!

**Comment by sundarnagarajan** [comment]
Thanks for your work on this.

BTW: I found some code on github, that allowed me to use compressed points for MANY curves:

[https://gist.github.com/kurtbrose/4423605#file-elliptic-py](file-elliptic.py)

[https://github.com/pyca/cryptography/issues/2346](2346)


Would you be interested in incorporating support for compressed points - it will reduce the size of PUBLIC keys by about 50%

**Comment by npmccallum** [comment]
SEC 1 point compression is already supported:
https://github.com/latchset/python-rubenesque/blob/master/rubenesque/codecs/sec.py#L30

**Comment by npmccallum** [comment]
(Point compression is, in fact, the default. You have to disable to get full X/Y values.)

**Comment by sundarnagarajan** [comment]
My mistake. I should look at this more carefully

**Comment by sundarnagarajan** [comment]
I see from the code that the TEST CODE only references curves **MDC201601, secp224r1, secp521r1, edwards25519, edwards448**

Does encode/decode also work for the following curves?
secp192r1, secp256r1, secp384r1, brainpoolP160r1, brainpoolP192r1, brainpoolP224r1, brainpoolP256r1, brainpoolP320r1, brainpoolP384r1, brainpoolP512r1

**Comment by npmccallum** [comment]
Yes. All encodings work for all curves.

**Comment by sundarnagarajan** [comment]
Awesome. Thanks
